#!/bin/bash

# Set the appropriate wallpaper based on month and hemisphere
# This will be run at login and periodically to update the wallpaper

LOGGER_TAG="bluefin-dynamic-wallpaper"
WALLPAPER_BASE_PATH="/usr/share/backgrounds/bluefin"

# Don't clobber custom wallpaper
CURRENT_WALLPAPER=$(gsettings get org.gnome.desktop.background picture-uri)
CURRENT_WALLPAPER=${CURRENT_WALLPAPER#\'file://}
CURRENT_WALLPAPER=${CURRENT_WALLPAPER%\'}

if [[ "$CURRENT_WALLPAPER" != ${WALLPAPER_BASE_PATH}/*-bluefin.xml ]]; then
    logger -t "$LOGGER_TAG" "User has a personal wallpaper set. Not changing it."
    exit 0
fi

MONTH=$(date +%m)
MONTH_NUM=${MONTH#0}  # Remove leading zero if present


LATITUDE=$(/usr/libexec/get-geoclue-latitude.py)
if [[ $? -ne 0 ]]; then
    logger -t "$LOGGER_TAG" "Falling back to Northern hemisphere (default)"
    HEMISPHERE="north"
else
    # Determine hemisphere
    if (( $(echo "$LATITUDE < 0" | bc -l) )); then
        HEMISPHERE="south"
        # Add 6 months and wrap around if needed
        MONTH_NUM=$(( (MONTH_NUM + 6 - 1) % 12 + 1 ))
    else
        HEMISPHERE="north"
    fi
fi

# Format month with leading zero if needed
if [[ $MONTH_NUM -lt 10 ]]; then
    MONTH_PADDED="0$MONTH_NUM"
else
    MONTH_PADDED="$MONTH_NUM"
fi

WALLPAPER_PATH="${WALLPAPER_BASE_PATH}/${MONTH_PADDED}-bluefin.xml"

if [[ ! -f "$WALLPAPER_PATH" ]]; then
    logger -t "$LOGGER_TAG" "Wallpaper file not found: $WALLPAPER_PATH"
    exit 1
fi

# Apply the wallpaper
gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER_PATH"
gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER_PATH"
logger -t "$LOGGER_TAG" "Set wallpaper to $WALLPAPER_PATH (adjusted month: $MONTH_NUM, hemisphere: $HEMISPHERE)"
